# Generated by Django 4.0.4 on 2022-05-10 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='TITLE')),
                ('category', models.CharField(max_length=10, verbose_name='CATEGORY')),
                ('email', models.TextField(blank=True, null=True, verbose_name='E-MAIL')),
                ('reply_via_email', models.BooleanField(default=False, verbose_name='REPLY via EMAIL')),
                ('telephone', models.TextField(blank=True, null=True, verbose_name='TELEPHONE')),
                ('reply_via_MMS', models.BooleanField(default=False, verbose_name='REPLY via MMS')),
                ('contents', models.TextField(verbose_name='CONTENTS')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='IMAGE')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_AT')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inquiry_created', to=settings.AUTH_USER_MODEL, verbose_name='CREATOR')),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('ACCOUNT', 'Account'), ('ETC.', 'etc.')], default='GENERAL', max_length=8, verbose_name='CATEGORY')),
                ('reply', models.TextField(verbose_name='REPLY')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED_AT')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FAQ_created_by', to=settings.AUTH_USER_MODEL, verbose_name='CREATOR')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FAQ_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='UPDATER')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='CONTENTS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED_AT')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_created', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Answer_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
