# Generated by Django 4.0.4 on 2022-05-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_answer_contents'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('Inquiry Registered', '문의 등록'), ('Inquiry Received', '접수 완료'), ('Answer Completed', '답변 완료')], default='Inquiry Registered', max_length=20, verbose_name='STATUS'),
        ),
    ]
