# Generated by Django 4.0.4 on 2022-04-18 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='TITLE')),
                ('category', models.CharField(max_length=10, verbose_name='CATEGORY')),
                ('email', models.TextField(verbose_name='E-MAIL')),
                ('reply_via_email', models.BooleanField(verbose_name='REPLY via EMAIL')),
                ('telephone', models.TextField(verbose_name='TELEPHONE')),
                ('reply_via_MMS', models.BooleanField(verbose_name='REPLY via MMS')),
                ('contents', models.TextField(verbose_name='CONTENTS')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='IMAGE')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField(verbose_name='CONTENTS')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED_AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED_AT')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inquiry_creator', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
                ('updater', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Inquiry_updater', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
