# Generated by Django 4.0.4 on 2022-04-17 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Question')),
                ('category', models.CharField(choices=[('GENERAL', 'General'), ('ACCOUNT', 'Account'), ('ETC.', 'etc.')], default='GENERAL', max_length=8, verbose_name='CATEGORY')),
                ('reply', models.TextField(verbose_name='REPLY')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='CREATED AT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='UPDATED AT')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FAQ_create', to=settings.AUTH_USER_MODEL, verbose_name='CREATOR')),
                ('updater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FAQ_update', to=settings.AUTH_USER_MODEL, verbose_name='UPDATER')),
            ],
        ),
    ]
