# Generated by Django 4.0.4 on 2022-04-17 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0002_alter_faq_created_at_alter_faq_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FAQ_creator', to=settings.AUTH_USER_MODEL, verbose_name='CREATOR'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FAQ_updater', to=settings.AUTH_USER_MODEL, verbose_name='UPDATER'),
        ),
    ]
